Функциональность Add controllers
MishanyaCh/java-shareit pull request #1
Opened 2024-02-05 12:55 UTC by MishanyaCh

Сдача на проверку практического задания спринта 13

2024-02-05 17:21 UTC, YazykovMikhail requested changes

2024-02-05 17:21 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        log.info("Пришел POST /items запрос с телом: {}", itemDto);
лог стоит поднял повыше, ведь запрос уже пришел, стоит залогировать, так же стоит логирвоать userId

2024-02-05 17:21 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +            throw new HeaderNotFoundException(message);
Лучше какое нибудь NPE выкидывать, ведь NotFound это когда не найден. А тут и искать нечего

2024-02-05 17:21 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/Storage/UserInMemoryStorageImpl.java
> +
можно сделать "индекс" для проверки уникальности имейлов
т.е добавить поле:
	private final Set<String> emailUniqSet = new HashSet<>();

и метод добавления пользователя будет выглядеть как нибуль во ттак:

```
public User save(User user) {
		final String email = user.getEmail();
		if (emailUniqSet.contains(email)) {
			throw new DataAlreadyExistException("Email: " + email + " already exists");
		}
		user.setId(++counter);
		storage.put(user.getId(), user);
		emailUniqSet.add(email);
		return user;
	}
```

2024-02-05 17:21 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/Storage/UserInMemoryStorageImpl.java
> +
Индексы будут в бд, тут он работает примерно так же)
Если будешь использовать, не забудь и метод uodate обновить

2024-02-06 22:43 UTC, MishanyaCh commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +            throw new HeaderNotFoundException(message);
поправил

2024-02-07 00:42 UTC, MishanyaCh commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        log.info("Пришел POST /items запрос с телом: {}", itemDto);
поправил

2024-02-07 00:50 UTC, MishanyaCh commented on src/main/java/ru/practicum/shareit/user/Storage/UserInMemoryStorageImpl.java
> +
Приму к сведению, что так можно сделать, да и код выглядит более изящно) Но пока править не буду, ибо как бы мне потом индексы не аукнулись... да и знания мои про индексы и как их использовать полностью отсутвуют

2024-02-07 16:38 UTC, YazykovMikhail approved these changes

2024-02-07 16:38 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/user/Storage/UserInMemoryStorageImpl.java
> +
Ну индексы еще будут проходится, просто тут реализация которую я покащывал была удобнее, чем постоянно пробегатсьтя по всему списку и проверять

2024-02-18 10:21 UTC, merged