Функциональность Add bookings
MishanyaCh/java-shareit pull request #2
Opened 2024-04-24 20:22 UTC by MishanyaCh

2024-04-27 17:49 UTC, YazykovMikhail requested changes

2024-04-27 17:49 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        log.info('\n' + "Пришел POST /bookings запрос с заголовком 'X-Sharer-User-Id' и телом: " +
перенос строк в логах обычно не используется, каждый лог пишется с новый строки всегда, так что особо это не нужно

2024-04-27 17:49 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
>   * TODO Sprint add-bookings.
Убирай раз реализовал, этот коммеентарий говорит о то, что нужно релализовать

2024-04-27 17:49 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/Service/BookingServiceImpl.java
> +        newBooking.setItem(savedItem); // добавляем данные о бронируемой вещи
маперры как раз для этого и используеются, что бы в коде не было массового количества set

```
        int itemId = newBooking.getItem().getId();
        Item savedItem = getItem(itemId); // находим вещь для бронирования в БД
        User savedUser = getUser(userId); // находим бронирующего вещь пользователя в БД
          Booking newBooking = bookingMapper.toBooking(bookingDto, savedItem, savedUser);
```
и статус тоже проставялй/или передавай и проставляй там же. 
и валидируй полностью этот обьект, а не каждый по отдельности

2024-04-27 17:49 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/Service/BookingServiceImpl.java
> +        newBooking.setItem(savedItem); // добавляем данные о бронируемой вещи
Поправь везде где есть много лишнх set, используй мапперы

2024-04-27 17:49 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
>   * TODO Sprint add-bookings.
поправь везде

2024-04-27 17:49 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                    @Valid @RequestBody BookingDtoForCreateBooking bookingDto) {
BookingDtoForCreateBooking -> BookingCreateRequestDto 
назови попроще и сразу понятно где и для чего исользуется

2024-04-27 17:49 UTC, YazykovMikhail commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public BookingDto createBooking(@RequestHeader(value = "X-Sharer-User-Id") Integer userId,
Так же с ответом, лучше BookingResponseDto - тоже сразу понятно где используется

2024-04-29 15:43 UTC, MishanyaCh commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
>   * TODO Sprint add-bookings.
исправил

2024-04-29 16:00 UTC, MishanyaCh commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        log.info('\n' + "Пришел POST /bookings запрос с заголовком 'X-Sharer-User-Id' и телом: " +
исправил

2024-04-29 16:18 UTC, MishanyaCh commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                    @Valid @RequestBody BookingDtoForCreateBooking bookingDto) {
исправил

2024-04-29 16:49 UTC, MishanyaCh commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public BookingDto createBooking(@RequestHeader(value = "X-Sharer-User-Id") Integer userId,
исправил

2024-04-30 13:54 UTC, MishanyaCh commented on src/main/java/ru/practicum/shareit/booking/Service/BookingServiceImpl.java
> +        newBooking.setItem(savedItem); // добавляем данные о бронируемой вещи
исправил

2024-05-01 13:55 UTC, YazykovMikhail approved these changes

2024-06-05 20:14 UTC, merged